//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardonerSistemas.Reports.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardonerSistemas.Reports.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward diagonal.
        /// </summary>
        internal static string StringBrushLinearGradientModeBackwardDiagonal {
            get {
                return ResourceManager.GetString("StringBrushLinearGradientModeBackwardDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward diagonal.
        /// </summary>
        internal static string StringBrushLinearGradientModeForwardDiagonal {
            get {
                return ResourceManager.GetString("StringBrushLinearGradientModeForwardDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string StringBrushLinearGradientModeHorizontal {
            get {
                return ResourceManager.GetString("StringBrushLinearGradientModeHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string StringBrushLinearGradientModeVertical {
            get {
                return ResourceManager.GetString("StringBrushLinearGradientModeVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear gradient.
        /// </summary>
        internal static string StringBrushTypeLinealGradient {
            get {
                return ResourceManager.GetString("StringBrushTypeLinealGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radial gradient.
        /// </summary>
        internal static string StringBrushTypeRadialGradient {
            get {
                return ResourceManager.GetString("StringBrushTypeRadialGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string StringBrushTypeSolid {
            get {
                return ResourceManager.GetString("StringBrushTypeSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string StringColor {
            get {
                return ResourceManager.GetString("StringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet.
        /// </summary>
        internal static string StringDatasourceProvidersDataSet {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODBC.
        /// </summary>
        internal static string StringDatasourceProvidersOdbc {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOdbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OleDb.
        /// </summary>
        internal static string StringDatasourceProvidersOleDb {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOleDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        internal static string StringDatasourceProvidersOracle {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server.
        /// </summary>
        internal static string StringDatasourceProvidersSqlServer {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure.
        /// </summary>
        internal static string StringDatasourceTypeStoredProcedure {
            get {
                return ResourceManager.GetString("StringDatasourceTypeStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table direct.
        /// </summary>
        internal static string StringDatasourceTypeTableDirect {
            get {
                return ResourceManager.GetString("StringDatasourceTypeTableDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string StringDatasourceTypeText {
            get {
                return ResourceManager.GetString("StringDatasourceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New *.
        /// </summary>
        internal static string StringFontNameNew {
            get {
                return ResourceManager.GetString("StringFontNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string StringGeneralNo {
            get {
                return ResourceManager.GetString("StringGeneralNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string StringGeneralYes {
            get {
                return ResourceManager.GetString("StringGeneralYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string StringPageOrientationLandscape {
            get {
                return ResourceManager.GetString("StringPageOrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string StringPageOrientationPortrait {
            get {
                return ResourceManager.GetString("StringPageOrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New *.
        /// </summary>
        internal static string StringReportNameNew {
            get {
                return ResourceManager.GetString("StringReportNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A0.
        /// </summary>
        internal static string StringReportPageSizeA0 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        internal static string StringReportPageSizeA1 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        internal static string StringReportPageSizeA2 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3.
        /// </summary>
        internal static string StringReportPageSizeA3 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string StringReportPageSizeA4 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5.
        /// </summary>
        internal static string StringReportPageSizeA5 {
            get {
                return ResourceManager.GetString("StringReportPageSizeA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B0.
        /// </summary>
        internal static string StringReportPageSizeB0 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1.
        /// </summary>
        internal static string StringReportPageSizeB1 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2.
        /// </summary>
        internal static string StringReportPageSizeB2 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3.
        /// </summary>
        internal static string StringReportPageSizeB3 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B4.
        /// </summary>
        internal static string StringReportPageSizeB4 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B5.
        /// </summary>
        internal static string StringReportPageSizeB5 {
            get {
                return ResourceManager.GetString("StringReportPageSizeB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crown.
        /// </summary>
        internal static string StringReportPageSizeCrown {
            get {
                return ResourceManager.GetString("StringReportPageSizeCrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demy.
        /// </summary>
        internal static string StringReportPageSizeDemy {
            get {
                return ResourceManager.GetString("StringReportPageSizeDemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Demy.
        /// </summary>
        internal static string StringReportPageSizeDoubleDemy {
            get {
                return ResourceManager.GetString("StringReportPageSizeDoubleDemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elephant.
        /// </summary>
        internal static string StringReportPageSizeElephant {
            get {
                return ResourceManager.GetString("StringReportPageSizeElephant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        internal static string StringReportPageSizeExecutive {
            get {
                return ResourceManager.GetString("StringReportPageSizeExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folio.
        /// </summary>
        internal static string StringReportPageSizeFolio {
            get {
                return ResourceManager.GetString("StringReportPageSizeFolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foolscap.
        /// </summary>
        internal static string StringReportPageSizeFoolscap {
            get {
                return ResourceManager.GetString("StringReportPageSizeFoolscap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Letter.
        /// </summary>
        internal static string StringReportPageSizeGovernmentLetter {
            get {
                return ResourceManager.GetString("StringReportPageSizeGovernmentLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Post.
        /// </summary>
        internal static string StringReportPageSizeLargePost {
            get {
                return ResourceManager.GetString("StringReportPageSizeLargePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        internal static string StringReportPageSizeLedger {
            get {
                return ResourceManager.GetString("StringReportPageSizeLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string StringReportPageSizeLegal {
            get {
                return ResourceManager.GetString("StringReportPageSizeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string StringReportPageSizeLetter {
            get {
                return ResourceManager.GetString("StringReportPageSizeLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string StringReportPageSizeMedium {
            get {
                return ResourceManager.GetString("StringReportPageSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string StringReportPageSizePost {
            get {
                return ResourceManager.GetString("StringReportPageSizePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quad Demy.
        /// </summary>
        internal static string StringReportPageSizeQuadDemy {
            get {
                return ResourceManager.GetString("StringReportPageSizeQuadDemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarto.
        /// </summary>
        internal static string StringReportPageSizeQuarto {
            get {
                return ResourceManager.GetString("StringReportPageSizeQuarto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA0.
        /// </summary>
        internal static string StringReportPageSizeRA0 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA1.
        /// </summary>
        internal static string StringReportPageSizeRA1 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA2.
        /// </summary>
        internal static string StringReportPageSizeRA2 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA3.
        /// </summary>
        internal static string StringReportPageSizeRA3 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA4.
        /// </summary>
        internal static string StringReportPageSizeRA4 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA5.
        /// </summary>
        internal static string StringReportPageSizeRA5 {
            get {
                return ResourceManager.GetString("StringReportPageSizeRA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal.
        /// </summary>
        internal static string StringReportPageSizeRoyal {
            get {
                return ResourceManager.GetString("StringReportPageSizeRoyal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10x14.
        /// </summary>
        internal static string StringReportPageSizeSize10x14 {
            get {
                return ResourceManager.GetString("StringReportPageSizeSize10x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        internal static string StringReportPageSizeStatement {
            get {
                return ResourceManager.GetString("StringReportPageSizeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STMT.
        /// </summary>
        internal static string StringReportPageSizeSTMT {
            get {
                return ResourceManager.GetString("StringReportPageSizeSTMT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabloid.
        /// </summary>
        internal static string StringReportPageSizeTabloid {
            get {
                return ResourceManager.GetString("StringReportPageSizeTabloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string StringSectionTypeDetail {
            get {
                return ResourceManager.GetString("StringSectionTypeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group footer.
        /// </summary>
        internal static string StringSectionTypeGroupFooter {
            get {
                return ResourceManager.GetString("StringSectionTypeGroupFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group header.
        /// </summary>
        internal static string StringSectionTypeGroupHeader {
            get {
                return ResourceManager.GetString("StringSectionTypeGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page footer.
        /// </summary>
        internal static string StringSectionTypePageFooter {
            get {
                return ResourceManager.GetString("StringSectionTypePageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page header.
        /// </summary>
        internal static string StringSectionTypePageHeader {
            get {
                return ResourceManager.GetString("StringSectionTypePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report footer.
        /// </summary>
        internal static string StringSectionTypeReportFooter {
            get {
                return ResourceManager.GetString("StringSectionTypeReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report header.
        /// </summary>
        internal static string StringSectionTypeReportHeader {
            get {
                return ResourceManager.GetString("StringSectionTypeReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string StringUndefined {
            get {
                return ResourceManager.GetString("StringUndefined", resourceCulture);
            }
        }
    }
}
