//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardonerSistemas.Reports.Net.WinformsEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardonerSistemas.Reports.Net.WinformsEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string StringApplyChanges {
            get {
                return ResourceManager.GetString("StringApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushes.
        /// </summary>
        internal static string StringBrushes {
            get {
                return ResourceManager.GetString("StringBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string StringColor {
            get {
                return ResourceManager.GetString("StringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource.
        /// </summary>
        internal static string StringDatasource {
            get {
                return ResourceManager.GetString("StringDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify connection string..
        /// </summary>
        internal static string StringDatasourceConnectionStringRequired {
            get {
                return ResourceManager.GetString("StringDatasourceConnectionStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the datasource?.
        /// </summary>
        internal static string StringDatasourceDeleteConfirmation {
            get {
                return ResourceManager.GetString("StringDatasourceDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the datasource field named &apos;{0}&apos;?.
        /// </summary>
        internal static string StringDatasourceFieldDeleteConfirmation {
            get {
                return ResourceManager.GetString("StringDatasourceFieldDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a field with this name..
        /// </summary>
        internal static string StringDatasourceFieldNameAlreadyExists {
            get {
                return ResourceManager.GetString("StringDatasourceFieldNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New *.
        /// </summary>
        internal static string StringDatasourceFieldNameNew {
            get {
                return ResourceManager.GetString("StringDatasourceFieldNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify name..
        /// </summary>
        internal static string StringDatasourceFieldNameRequired {
            get {
                return ResourceManager.GetString("StringDatasourceFieldNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a new field created..
        /// </summary>
        internal static string StringDatasourceFieldNewAlreadyExists {
            get {
                return ResourceManager.GetString("StringDatasourceFieldNewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string StringDatasourceFields {
            get {
                return ResourceManager.GetString("StringDatasourceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add field.
        /// </summary>
        internal static string StringDatasourceFieldsAdd {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} fields..
        /// </summary>
        internal static string StringDatasourceFieldsCounter {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not fields..
        /// </summary>
        internal static string StringDatasourceFieldsCounterEmpty {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsCounterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one field..
        /// </summary>
        internal static string StringDatasourceFieldsCounterOne {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsCounterOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to refresh the fields of the datasource?.
        /// </summary>
        internal static string StringDatasourceFieldsGetConfirmation {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsGetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are parameters with unspecified values. Do you want to continue anyway?.
        /// </summary>
        internal static string StringDatasourceFieldsGetWithNullParametersConfirmation {
            get {
                return ResourceManager.GetString("StringDatasourceFieldsGetWithNullParametersConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify type..
        /// </summary>
        internal static string StringDatasourceFieldTypeRequired {
            get {
                return ResourceManager.GetString("StringDatasourceFieldTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the datasource parameter named &apos;{0}&apos;?.
        /// </summary>
        internal static string StringDatasourceParameterDeleteConfirmation {
            get {
                return ResourceManager.GetString("StringDatasourceParameterDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a parameter with this name..
        /// </summary>
        internal static string StringDatasourceParameterNameAlreadyExists {
            get {
                return ResourceManager.GetString("StringDatasourceParameterNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New *.
        /// </summary>
        internal static string StringDatasourceParameterNameNew {
            get {
                return ResourceManager.GetString("StringDatasourceParameterNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify name..
        /// </summary>
        internal static string StringDatasourceParameterNameRequired {
            get {
                return ResourceManager.GetString("StringDatasourceParameterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a new parameter created..
        /// </summary>
        internal static string StringDatasourceParameterNewAlreadyExists {
            get {
                return ResourceManager.GetString("StringDatasourceParameterNewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string StringDatasourceParameters {
            get {
                return ResourceManager.GetString("StringDatasourceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parameter.
        /// </summary>
        internal static string StringDatasourceParametersAdd {
            get {
                return ResourceManager.GetString("StringDatasourceParametersAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} parameters..
        /// </summary>
        internal static string StringDatasourceParametersCounter {
            get {
                return ResourceManager.GetString("StringDatasourceParametersCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not parameters..
        /// </summary>
        internal static string StringDatasourceParametersCounterEmpty {
            get {
                return ResourceManager.GetString("StringDatasourceParametersCounterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one parameter..
        /// </summary>
        internal static string StringDatasourceParametersCounterOne {
            get {
                return ResourceManager.GetString("StringDatasourceParametersCounterOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify type..
        /// </summary>
        internal static string StringDatasourceParameterTypeRequired {
            get {
                return ResourceManager.GetString("StringDatasourceParameterTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify provider..
        /// </summary>
        internal static string StringDatasourceProviderRequired {
            get {
                return ResourceManager.GetString("StringDatasourceProviderRequired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Must specify text..
        /// </summary>
        internal static string StringDatasourceTextRequired {
            get {
                return ResourceManager.GetString("StringDatasourceTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify type..
        /// </summary>
        internal static string StringDatasourceTypeRequired {
            get {
                return ResourceManager.GetString("StringDatasourceTypeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report files (*.csrpt)|*.csrpt|All files (*.*)|*.*.
        /// </summary>
        internal static string StringFileDialogFilter {
            get {
                return ResourceManager.GetString("StringFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the font &apos;{0}&apos;?.
        /// </summary>
        internal static string StringFontDeleteConfirmation {
            get {
                return ResourceManager.GetString("StringFontDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New *.
        /// </summary>
        internal static string StringFontNameNew {
            get {
                return ResourceManager.GetString("StringFontNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a new font created..
        /// </summary>
        internal static string StringFontNewAlreadyExists {
            get {
                return ResourceManager.GetString("StringFontNewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string StringFonts {
            get {
                return ResourceManager.GetString("StringFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add font.
        /// </summary>
        internal static string StringFontsAdd {
            get {
                return ResourceManager.GetString("StringFontsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} fonts..
        /// </summary>
        internal static string StringFontsCounter {
            get {
                return ResourceManager.GetString("StringFontsCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not fonts..
        /// </summary>
        internal static string StringFontsCounterEmpty {
            get {
                return ResourceManager.GetString("StringFontsCounterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one font..
        /// </summary>
        internal static string StringFontsCounterOne {
            get {
                return ResourceManager.GetString("StringFontsCounterOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string StringLines {
            get {
                return ResourceManager.GetString("StringLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - (count: {0}).
        /// </summary>
        internal static string StringNodeItemsCount {
            get {
                return ResourceManager.GetString("StringNodeItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles.
        /// </summary>
        internal static string StringRectangles {
            get {
                return ResourceManager.GetString("StringRectangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report has unsaved changes.
        ///Do you want to save them?.
        /// </summary>
        internal static string StringReportModifiedConfirmation {
            get {
                return ResourceManager.GetString("StringReportModifiedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New report *.
        /// </summary>
        internal static string StringReportNameNew {
            get {
                return ResourceManager.GetString("StringReportNameNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify name..
        /// </summary>
        internal static string StringReportNameRequired {
            get {
                return ResourceManager.GetString("StringReportNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify page orientation..
        /// </summary>
        internal static string StringReportPageOrientationRequired {
            get {
                return ResourceManager.GetString("StringReportPageOrientationRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must specify page size..
        /// </summary>
        internal static string StringReportPageSizeRequired {
            get {
                return ResourceManager.GetString("StringReportPageSizeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string StringResetChanges {
            get {
                return ResourceManager.GetString("StringResetChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string StringSections {
            get {
                return ResourceManager.GetString("StringSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texts.
        /// </summary>
        internal static string StringTexts {
            get {
                return ResourceManager.GetString("StringTexts", resourceCulture);
            }
        }
    }
}
