//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardonerSistemas.Reports.Net.WinformsEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardonerSistemas.Reports.Net.WinformsEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brushes.
        /// </summary>
        internal static string StringBrushes {
            get {
                return ResourceManager.GetString("StringBrushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string StringColor {
            get {
                return ResourceManager.GetString("StringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasource.
        /// </summary>
        internal static string StringDatasource {
            get {
                return ResourceManager.GetString("StringDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSet.
        /// </summary>
        internal static string StringDatasourceProvidersDataSet {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODBC.
        /// </summary>
        internal static string StringDatasourceProvidersOdbc {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOdbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OleDb.
        /// </summary>
        internal static string StringDatasourceProvidersOleDb {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOleDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle.
        /// </summary>
        internal static string StringDatasourceProvidersOracle {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersOracle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server.
        /// </summary>
        internal static string StringDatasourceProvidersSqlServer {
            get {
                return ResourceManager.GetString("StringDatasourceProvidersSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure.
        /// </summary>
        internal static string StringDatasourceTypeStoredProcedure {
            get {
                return ResourceManager.GetString("StringDatasourceTypeStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table direct.
        /// </summary>
        internal static string StringDatasourceTypeTableDirect {
            get {
                return ResourceManager.GetString("StringDatasourceTypeTableDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string StringDatasourceTypeText {
            get {
                return ResourceManager.GetString("StringDatasourceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        internal static string StringFonts {
            get {
                return ResourceManager.GetString("StringFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string StringLines {
            get {
                return ResourceManager.GetString("StringLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string StringPageOrientationLandscape {
            get {
                return ResourceManager.GetString("StringPageOrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string StringPageOrientationPortrait {
            get {
                return ResourceManager.GetString("StringPageOrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangles.
        /// </summary>
        internal static string StringRectangles {
            get {
                return ResourceManager.GetString("StringRectangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * New report *.
        /// </summary>
        internal static string StringReportNew {
            get {
                return ResourceManager.GetString("StringReportNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string StringSections {
            get {
                return ResourceManager.GetString("StringSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texts.
        /// </summary>
        internal static string StringTexts {
            get {
                return ResourceManager.GetString("StringTexts", resourceCulture);
            }
        }
    }
}
